### ISSUE TITLE
couldn't find the core code file that implements "Skew-Fit". 

### ISSUE THREAD

**Issue by COST-97** [vitchyr/rlkit#100]
I looked up the code carefully, but couldn't find the core code file that implements "Skew-Fit". Could you give me some advice? thank you very much.

**Comment by vitchyr** [comment]
See here: https://github.com/vitchyr/rlkit/blob/f136e140a57078c4f0f665051df74dffb1351f33/rlkit/data_management/online_vae_replay_buffer.py#L227
