### ISSUE TITLE
[solved] ResolvePackageNotFound error when installing the conda environment 

### ISSUE THREAD

**Issue by PierreExeter** [vitchyr/rlkit#107]
Hello,

I solved this issue myself but I thought it may be useful to write it here in case other people face the same issue.

When installing the Linux GPU conda environment
```bash
conda env create -f linux-gpu-env.yml
```

it returns this error:

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - joblib=0.9.4
  - numba==0.35.0=np111py35_0
  - matplotlib==2.0.2=np111py35_0
```

As suggested [here](https://stackoverflow.com/questions/58219956/how-to-fix-resolvepackagenotfound-error-when-creating-conda-environment), I used this command instead:
```bash
CONDA_RESTORE_FREE_CHANNEL=1 conda env create -f linux-gpu-env.yml
```

Tested on 
- Ubuntu 18.04
- conda 4.8.1

**Comment by zadaianchuk** [comment]
Should this line be in README.md?
`CONDA_RESTORE_FREE_CHANNEL=1 conda env create -f linux-gpu-env.yml`
