### ISSUE TITLE
Box2D-kengz installation crashing

### ISSUE THREAD

**Issue by vitchyr** [vitchyr/rlkit#11]
![box2d-crash](https://user-images.githubusercontent.com/1297125/45233422-8a92b680-b287-11e8-9677-fe8461628b13.png)
Seems to happen when building from Anaconda.

**Comment by dangeng** [comment]
I ran `sudo apt-get install swig` and then built the environment and it worked (not sure why it worked though...)

**Comment by vitchyr** [comment]
Looks like this was specific to one computer, so I'm going to close this unless someone else has this issue.
