### ISSUE TITLE
New tag for version before AWAC commit

### ISSUE THREAD

**Issue by ksluck** [vitchyr/rlkit#117]
Any chance you could maybe create a new tag for the state of the master branch before the AWAC commit a few days ago? 
It seems quite many files were changed/moved during that commit such that some of my code which uses rlkit breaks.

Thanks in advance!

**Comment by ksluck** [comment]
I guess this is resolved? ;) 
https://github.com/vitchyr/rlkit/tree/v0.2.1

Closing the issue then

Thanks!

**Comment by vitchyr** [comment]
Haha, yup! I forgot to comment here. Thanks for the suggestion!
