### ISSUE TITLE
evaluation/env_infos/failed Mean = 0.0

### ISSUE THREAD

**Issue by liuqi8827** [vitchyr/rlkit#133]
Thanks your great work.
I'm facing a problem of getting the information of **evaluation/env_infos/failed Mean**.
I found that the output of evaluation/env_infos/failed Mean always equal to **0.0**. 
It never changed.

```
evaluation/env_infos/final/failed Mean    0.0
evaluation/env_infos/final/failed Std     0.0
evaluation/env_infos/final/failed Max     False
evaluation/env_infos/final/failed Min     False
evaluation/env_infos/initial/failed Mean  0.0
evaluation/env_infos/initial/failed Std   0.0
evaluation/env_infos/initial/failed Max   False
evaluation/env_infos/initial/failed Min   False
evaluation/env_infos/failed Mean          0.0
evaluation/env_infos/failed Std           0.0
evaluation/env_infos/failed Max           False
evaluation/env_infos/failed Min           False
```

Can you give some suggestions?

Thanks a lot!

**Comment by vitchyr** [comment]
Hi, are you sure that this is a logging issue? Could it be that failed is always equal to 0 in your environment?

**Comment by liuqi8827** [comment]
@vitchyr Thanks for your reply.

It's my fault.
