### ISSUE TITLE
Compatible with Windows system？

### ISSUE THREAD

**Issue by AmyWorkspace** [vitchyr/rlkit#135]
Hi, I noticed there are linux and mac env files in environment folder. I tried the Windows Subsystem for Linux(WSL), but got stuck at the step of get computer id in WSL for MuJoCo. I wonder whether this framework can be run in Window 10 system directly. 

Appreciate any feedbacks and suggestions. Thanks.

**Comment by vitchyr** [comment]
Hi @AmyWorkspace , unfortunately I don't plan on supporting Windows. If your issue is with installing Mujoco, I suggest posting on the Mujoco forum.
