### ISSUE TITLE
Remove incorrect update date from readme

### ISSUE THREAD

**Issue by impredicative** [vitchyr/rlkit#15]
The readme says:

> README last updated on: 02/19/2018

This date is incorrect in the literal sense of the word "update". It doesn't make sense to have this displayed in the readme. I recommend either removing it, or turning it into a hidden comment.

For example:
```<!-- This is how to write a hidden comment. -->```

**Comment by vitchyr** [comment]
Good point--it's rather unnecessary. Will do and thanks!
