### ISSUE TITLE
SAC code fails?

### ISSUE THREAD

**Issue by simitii** [vitchyr/rlkit#2]
Hi. I tried running SAC but it fails with following error. I am currently working on your repo to add environment farming(multiple instance of an environment feeding the reinforcement learning algorithms) feature. Therefore, problem may be related to my environment or changed parts but it seem like it is not since DDPG works. Do you have any idea why SAC fails? Thanks.

>   File "/root/code/rlkit/core/rl_algorithm.py", line 134, in train
>     self.train_online(start_epoch=start_epoch)
>   File "/root/code/rlkit/core/rl_algorithm.py", line 210, in train_online
>     observation = self.play_one_step(observation)
>   File "/root/code/rlkit/core/rl_algorithm.py", line 179, in play_one_step
>     self._try_to_train()
>   File "/root/code/rlkit/core/rl_algorithm.py", line 222, in _try_to_train
>     self._do_training()
>   File "/root/code/rlkit/torch/sac/sac.py", line 131, in _do_training
>     policy_loss.backward()
>   File "/opt/conda/envs/rlkit-env/lib/python3.5/site-packages/torch/autograd/variable.py", line 156, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
>   File "/opt/conda/envs/rlkit-env/lib/python3.5/site-packages/torch/autograd/__init__.py", line 98, in backward
>     variables, grad_variables, retain_graph)
>   File "/opt/conda/envs/rlkit-env/lib/python3.5/site-packages/torch/autograd/stochastic_function.py", line 15, in _do_backward
>     raise RuntimeError("differentiating stochastic functions requires "
> RuntimeError: differentiating stochastic functions requires providing a reward

**Comment by vitchyr** [comment]
What version of PyTorch are you using? I haven't seen this error before, this code is written for PyTorch 0.3.0 (see rlkit/docker/rlkit/rlkit-env.yml), so my current suspicion is that it's a versioning issue.

Are you using v0.2.0? If so, there's some discussion of this [here](https://github.com/uber/pyro/issues/68). Or perhaps using a version before [this issue was resolved](https://github.com/pytorch/pytorch/issues/685)?

**Comment by simitii** [comment]
I directly install the environment from the given Dockerfile and rlkit-env.yml files. But you are right. I was somehow using v0.2.0. I will try v0.3.0 and comment if it works. By the way rlkit/docker/rlkit/rlkit-env.yml does not specifies the version of PyTorch and v0.3.0 is not available main conda repos. https://github.com/pytorch/pytorch/issues/4629
Thanks.

**Comment by vitchyr** [comment]
Glad to hear it worked. By thje way, the .yml file has pytorch getting installed via pip for that reason (git+git://github.com/pytorch/pytorch.git@v0.3.0).
