### ISSUE TITLE
HER/RIG example scripts expect "scripts" folder to be in "rlkit/scripts"

### ISSUE THREAD

**Issue by richardrl** [vitchyr/rlkit#21]
Whenever I run the example scripts (and my own) they get fileNotFound errors because run_experiment expects "scripts" to be in the rlkit/rlkit directory not at the root level

**Comment by cww97** [comment]
I cannot remember how I fixed it exactly, have u added `multi-world`, `doodad` into PYTHONPATH ?

**Comment by vitchyr** [comment]
Ah, it was because I forgot to call the parent dir. Fixed with 1da0ff3f99844fd600a4353109d5c767f5b60a9c.
