### ISSUE TITLE
Retrieve s3

### ISSUE THREAD

**Issue by richardrl** [vitchyr/rlkit#26]
Is there any easy way to get the S3 path? I'd like to have a script that downloads all the recent s3 results instead of copy and pasting each time, and that would require having the s3 path returned each time an experiment is uploaded

**Comment by vitchyr** [comment]
I use the [AWS command line interface](https://docs.aws.amazon.com/cli/latest/reference/s3/):
```
aws s3 sync s3://bucket-name/path/ /home/path/to/local/dir
```
The s3 bucket path should be the same as the one in `rlkit.launchers.config.AWS_S3_PATH`.
