### ISSUE TITLE
error : mujoco_py' has no attribute 'load_model_from_path  mujoco_py version 0.5.7

### ISSUE THREAD

**Issue by zdx3578** [vitchyr/rlkit#3]
fix by  https://github.com/openai/mujoco-py/issues/188
use gym 0.7

other: 
conda install pytorch=0.3.0 torchvision -c pytorch
pip install gym==0.7.3

  541  export PYTHONPATH='.'
  549  pip install mujoco-py==0.5.7
  567  pip install gym==0.7.3
  587  conda install pytorch=0.3.0 torchvision -c pytorch

**Comment by zdx3578** [comment]
my env :+1: 

(rlkit-env) test@frankwang-Tri01:~/anaconda3/pkgs$ conda env export

name: rlkit-env
channels:
  - pytorch
  - soumith
  - menpo
  - kne
  - defaults
dependencies:
  - backcall=0.1.0=py35_0
  - bleach=2.1.3=py35_0
  - bokeh=0.12.15=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py35_0
  - cffi=1.11.5=py35h9745a5d_0
  - click=6.7=py35h353a69f_0
  - cloudpickle=0.5.2=py35_1
  - colorama=0.3.7=py35_0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cycler=0.10.0=py35hc4d5149_0
  - cytoolz=0.9.0.1=py35h14c3975_0
  - dask=0.17.4=py35_0
  - dask-core=0.17.4=py35_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py35_0
  - distributed=1.21.8=py35_0
  - entrypoints=0.2.3=py35h48174a2_2
  - expat=2.2.5=he0dffb1_0
  - flask=0.12.2=py35h679e90e_0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.7.1=py35h8d53cdc_0
  - hdf5=1.10.1=h9caa474_1
  - heapdict=1.0.0=py35_2
  - html5lib=1.0.1=py35h2f9c1c0_0
  - icu=54.1=0
  - imageio=2.3.0=py35_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py35_0
  - ipython=6.3.1=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.2.1=py35_0
  - itsdangerous=0.24=py35h7c46880_1
  - jedi=0.12.0=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - joblib=0.9.4=py35_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35ha89e94b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.14=0
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.4=0
  - llvmlite=0.22.0=py35h998887b_0
  - locket=0.2.0=py35h170bc82_1
  - mako=1.0.7=py35h69899ea_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.0.2=np111py35_0
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2018.0.2=1
  - msgpack-python=0.5.6=py35h6bb024c_0
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - nccl=1.3.4=cuda8.0_1
  - networkx=1.11=py35hf333c83_0
  - ninja=1.8.2=h6bb024c_1
  - notebook=5.4.1=py35_0
  - numba=0.37.0=np111py35h3e3e0ff_0
  - numpy=1.11.3=py35h3dfced4_4
  - olefile=0.45.1=py35_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py35_0
  - pandas=0.21.1=py35h20b78c2_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py35h1565a15_1
  - parso=0.2.0=py35_0
  - partd=0.3.8=py35h68187f2_0
  - path.py=11.0.1=py35_0
  - pcre=8.42=h439df22_0
  - pexpect=4.5.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=4.2.1=py35_0
  - pip=10.0.1=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - psutil=5.4.5=py35h14c3975_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - pycparser=2.18=py35h61b3040_1
  - pygments=2.2.0=py35h0f41973_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.6.0=py35h0e41ada_5
  - python=3.5.2=0
  - python-dateutil=2.7.2=py35_0
  - pytz=2018.4=py35_0
  - pywavelets=0.5.2=py35h53ec731_0
  - pyyaml=3.12=py35h46ef4ae_1
  - pyzmq=17.0.0=py35h14c3975_0
  - qt=5.6.2=5
  - readline=6.2=2
  - scikit-image=0.13.1=py35h7a281a6_0
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.0.1=py35hfc37229_0
  - send2trash=1.5.0=py35_0
  - setuptools=39.1.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.18.1=py35h9eaea60_2
  - six=1.11.0=py35h423b573_1
  - sortedcontainers=1.5.10=py35_0
  - sqlite=3.13.0=0
  - tblib=1.3.2=py35hf1eb0b4_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.5.18=0
  - toolz=0.9.0=py35_0
  - tornado=5.0.2=py35_0
  - traitlets=4.3.2=py35ha522a97_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.0=py35_0
  - widgetsnbextension=3.2.1=py35_0
  - xz=5.2.3=h5e939de_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=h439df22_0
  - zict=0.1.3=py35h29275ca_0
  - zlib=1.2.11=ha838bed_2
  - pybox2d=2.3.1post2=py35_0
  - pygame=1.9.2a0=py35_0
  - opencv3=3.1.0=py35_0
  - pytorch=0.3.0=py35_cuda8.0.61_cudnn7.0.3hb362f6e_4
  - torchvision=0.2.0=py35heaa392f_1
  - cuda80=1.0=0
  - pip:
    - atari-py==0.1.1
    - attrs==18.1.0
    - awscli==1.15.15
    - botocore==1.10.15
    - box2d==2.3.1
    - cached-property==1.4.2
    - catkin-pkg==0.4.2
    - chardet==3.0.4
    - coverage==4.5.1
    - cython==0.28.2
    - docutils==0.14
    - dominate==2.3.1
    - enum34==1.1.6
    - flatbuffers==2015.12.22.1
    - funcsigs==1.0.2
    - future==0.16.0
    - gitdb2==2.0.3
    - gitpython==2.1.9
    - glfw==1.6.0
    - gtimer==1.0.0b5
    - gym==0.7.3
    - idna==2.6
    - ipdb==0.11
    - jmespath==0.9.3
    - jupyter==1.0.0
    - jupyter-console==5.2.0
    - lasagne==0.1
    - line-profiler==2.1.2
    - more-itertools==4.1.0
    - mujoco-py==0.5.7
    - nose2==0.7.4
    - plotly==2.5.1
    - pluggy==0.6.0
    - prettytensor==0.7.4
    - progressbar2==3.37.1
    - py==1.5.3
    - pyasn1==0.4.2
    - pyglet==1.3.2
    - pyopengl==3.1.0
    - pyprind==2.11.2
    - pytest==3.5.1
    - python-utils==2.3.0
    - qtconsole==4.3.1
    - ray==0.4.0
    - redis==2.10.6
    - requests==2.18.4
    - rospkg==1.1.4
    - rsa==3.4.2
    - s3transfer==0.1.13
    - seaborn==0.8.1
    - smmap2==2.0.3
    - snakeviz==0.4.2
    - torch==0.3.0.post4
    - urllib3==1.22
prefix: /home/test/anaconda3/envs/rlkit-env

(rlkit-env) test@frankwang-Tri01:~/anaconda3/pkgs$ 
(rlkit-env) test@frankwang-Tri01:~/anaconda3/pkgs$

**Comment by zdx3578** [comment]
[env.txt](https://github.com/vitchyr/rlkit/files/1982867/env.txt)

**Comment by vitchyr** [comment]
Thanks for pointing this out. I'll post a .yml file that has the specific versions and is more minimal soon (later today or tomorrow). Hopefully that will fix some of the versioning issues that you (and other people) have brought up.

**Comment by vitchyr** [comment]
Addressed with 2c8561d82f8a4c61d00f2164c41e7a3cdac8e19d.

The rlkit-env.yml file is *much* smaller now and gives the specific library versions.
