### ISSUE TITLE
Unable to reproduce the results of HER-TD3

### ISSUE THREAD

**Issue by charliezon** [vitchyr/rlkit#30]
When I first run the script with:

`python -m examples.her.her_td3_gym_fetch_reach`

It raised an error:

```
Traceback (most recent call last):
  File "/home/fcloud/anaconda3/envs/rlkit/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fcloud/anaconda3/envs/rlkit/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fcloud/workspace/rlkit/examples/her/her_td3_gym_fetch_reach.py", line 88, in <module>
    experiment(variant)
  File "/home/fcloud/workspace/rlkit/examples/her/her_td3_gym_fetch_reach.py", line 65, in experiment
    **variant['algo_kwargs']
TypeError: __init__() missing 2 required keyword-only arguments: 'her_kwargs' and 'td3_kwargs'
```

So I modified the source code as follows:

```
    her_kwargs = dict(observation_key='observation', desired_goal_key='desired_goal')
    td3_kwargs = dict(env=env,
                      qf1=qf1,
                      qf2=qf2,
                      policy=policy,
                      exploration_policy=exploration_policy)
    algorithm = HerTd3(
        her_kwargs=her_kwargs,
        td3_kwargs=td3_kwargs,
        replay_buffer=replay_buffer,
        **variant['algo_kwargs']
    )
```

Then the experiment can be launched successfully, but the results seem not correct:
![newplot](https://user-images.githubusercontent.com/3232771/51584821-f5c8e680-1f11-11e9-84ae-b51c7d62e94a.png)

**Comment by richardrl** [comment]
In my experience the reacher will usually end up working with the default settings in that script, but it may take many more epochs than the screenshot in the HER Readme. However, the other tasks I have not gotten to work

**Comment by vitchyr** [comment]
I just ran 5 seeds of the example script and got the following results:
![image](https://user-images.githubusercontent.com/1297125/51816617-3317d600-227c-11e9-8cc9-ea6c881f49b9.png)
So while the variance across seeds might be high (one seed fails completely, the others 4 succeed), I'm going to close this issue since it seems to be working.

**Comment by richardrl** [comment]
@vitchyr Hey vitchyr how do you get the plots to separate as individual lines per seed versus accumulating as variance shading over one line?

**Comment by vitchyr** [comment]
Split by `exp_name` or `unique_id`.

**Comment by patrickcho168** [comment]
The comments at the top of the HER scripts are confusing ("This should results in an average return of ~3000 by the end of training."). I think they aren't meant for the environments in the script?
