### ISSUE TITLE
Training env is reset at start of epoch, but PathBuilder not reset. Resulting in erroneous Exploration statistics.

### ISSUE THREAD

**Issue by pimdh** [vitchyr/rlkit#36]
Hi Vitchyr!

There appears to be an issue in the Exploration statistics. In online training, at each new epoch, `            observation = self._start_new_rollout()` is called. However, the PathBuilder is not reset at the end of an epoch, so the first trajectory of each new epoch is appended to the last trajectory of the previous epoch. This results in the wrong exploration returns statistics. I don't believe the rest of the training is affected.

One solution could be to call `self._handle_rollout_ending` at the end of each epoch. This would however also yields returns of episodes that are cut short, but I'd say that's preferable. Shall I file a PR?

Nice work on this repo!

Best,
Pim

**Comment by vitchyr** [comment]
Hi Pim!

Thanks for catching this and the kind words. Another alternative is to just reset `self._current_path_builder` in `_start_epoch`. This results in the last trajectory getting thrown away, so maybe we could add a check to see if that happens and then print a warning for the user (and let the user decide if they want to handle that).

My main concern with silently calling `self._handle_rollout_ending` is that this could have some unexpected behaviors that could result in bugs if people aren't aware of it.

What do you think?

Vitchyr

**Comment by pimdh** [comment]
I'm not sure what's wise. Note that it has some consequence for evaluation as well. Eval is not triggered when `self._handle_rollout_ending` is not called since the last eval. Calling `self._handle_rollout_ending` after each epoch makes that eval is never skipped. The current behaviour is btw not ideal, as then it becomes very random whether eval is skipped or not.

I'd say calling `self._handle_rollout_ending` after each epoch + adding a note in the docstring is the most sensible. The rollout is also ended after (as the env is reset), so that new behaviour doesn't contradict the semantics of the name.

**Comment by vitchyr** [comment]
@pimdh I'm working on a (semi-large) refactor which will hopefully fix this. The main idea is that I think I'll abstract the sampling code into its own, separate module so that `RLAlgorithm` doesn't have to reason about episodes ending.

**Comment by vitchyr** [comment]
Fixed with v0.2 and specifically 7290c19623ca29e0affa8068488487132f2b8ed3
