### ISSUE TITLE
Use stable implementation of tanh's inverse log determinant Jacobian

### ISSUE THREAD

**Issue by alexlee-gk** [vitchyr/rlkit#37]
Replace the second term from https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/distributions.py#L43-L44 with the equation from
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/bijectors/tanh.py#L73 .

That is, replace `torch.log(1 - value * value + self.epsilon` with `2. * (log(2.) - pre_tanh_value - softplus(-2. * pre_tanh_value))`.

**Comment by vitchyr** [comment]
Implemented in c1e9ec6b6aa6b9cd1c3139f118eed0201dea9fd2.
