### ISSUE TITLE
The policy loss in SAC?

### ISSUE THREAD

**Issue by zhaoyingnan179346** [vitchyr/rlkit#38]
thanks for your code,it helps a lot. I wonder why you use a different policy loss in SAC. 
![2019-03-28 19-54-25屏幕截图](https://user-images.githubusercontent.com/16360301/55155837-56cf9d80-5193-11e9-9c52-883cb4996e94.png)
In the origin paper, the policy loss is simple. What does the mean_reg_loss and other loss mean?Hoping for your reply.

**Comment by vitchyr** [comment]
This was based on an old version of SAC. You can set the `policy_pre_activation_weight` and the `reg_weight`s to zero to get the (updated) SAC loss. I'm planning on removing this in the future, and I'll make this as closed. Feel free to follow-up with other questions.
