### ISSUE TITLE
Value network in TwinSAC

### ISSUE THREAD

**Issue by jendelel** [vitchyr/rlkit#40]
Hi, 

I skimmed over the author's implementation and it seems that they don't use the value network. Instead they only use the Q-networks. Seems they removed it in [this commit](https://github.com/rail-berkeley/softlearning/commit/d33c114816429c494e2a40625849d57ae2103f3f#diff-1c64d7ee5ec9fc6ed8210fb75352123f)

Thanks, 

Lukas

**Comment by vitchyr** [comment]
Yes, this is a known difference. I've been updating the code quite a bit, and that's one of the changes made. I'm not ready to merge the new code into master just yet, but it's in the `v0.2` branch that I just pushed. The SAC code has been tested. I'm not merging it into master yet is because I still need to do small things, like updating the documentation.

**Comment by quanvuong** [comment]
Hi,

When you mention the SAC code has been tested, do you mean that its performance is the same as the performance of the Tensorflow implementation?

Thanks!

**Comment by vitchyr** [comment]
Yes, when tested on ant, walker, hopper, humanoid, and half cheetah. This has now been merged into master.

**Comment by quanvuong** [comment]
Thank you for your reply! Sorry to open this up again, but I am unable to obtain comparable result to the Tensorflow implementation using the master branch. I post the training graph for the pytorch and tensorflow implementation below for comparison

![TSAC Hopper-v2 Pytorch](https://user-images.githubusercontent.com/6988600/55760474-b9eee900-5a4b-11e9-9921-1df8ed5e99ad.png)

![TSAC Hopper-v2 TF](https://user-images.githubusercontent.com/6988600/55760494-cd01b900-5a4b-11e9-86c9-033515c21b70.png)

The TF implementation's final performance is higher and also learns faster. The shape of the TF implementation also closely matches the shape of the graph in the paper, i.e. quickly increase and plateau at around 400 epochs.

Does the pytorch graph look similar to what you obtained too? 

I just want to mention that your repo is awesome. Answering pestering question from me is not your responsibility : ) and I really appreciate any help here.
