### ISSUE TITLE
Future entropy missed in SAC.

### ISSUE THREAD

**Issue by brickerino** [vitchyr/rlkit#43]
Hello!
It seems that in the current version of the code future policy entropy is missing from target value.
https://github.com/vitchyr/rlkit/blob/76be8716881d9674082991bf33a65243003144d1/rlkit/torch/sac/sac.py#L105

**Comment by vitchyr** [comment]
Great catch! It's easy to add back, but let me first test that everything still works, and then I'll push the corresponding change.

**Comment by vitchyr** [comment]
@brickerino I actually just pushed the change. I'll leave this issue open until all my tests (the example scripts) are done running. Thanks for catching this.

**Comment by vitchyr** [comment]
Okay, it seems to work well! For example, here's the performance on hopper:

![image](https://user-images.githubusercontent.com/1297125/56074311-c08ba200-5d64-11e9-9dd4-a879433ad3e5.png)

as well as other envs:

![image](https://user-images.githubusercontent.com/1297125/56074317-d7ca8f80-5d64-11e9-8175-1915f948fe51.png)

Thanks again for catching this.

**Comment by brickerino** [comment]
Thank for the fix! Was glad to help.
