### ISSUE TITLE
Make sure you dont need a Mujoco license to use any of the algorithms

### ISSUE THREAD

**Issue by redknightlois** [vitchyr/rlkit#48]
There are many algorithms that import Mujoco environments because they are not separated. In my case I dont care about Mujoco, in fact I had to get a trial license just to avoid having to remove code from my fork.

**Comment by vitchyr** [comment]
I don't think any of the algorithm import mujoco. Do you have a specific file in mind? The example scripts certainly do. Is that what you're referring to?

**Comment by redknightlois** [comment]
In the chain of imports, for example VAE will import some environment proxies specific for mujoco. Is it ok if I move around that in a PR?

**Comment by vitchyr** [comment]
Oh I see. Yes, definitely feel free to make a PR for it.

**Comment by gerritschoe** [comment]
Outcommenting `import mujoco_py` in [wrappers.py](../blob/master/rlkit/envs/wrappers.py) solved this for me. I am using Soft Actor-Critic without Mujoco.

**Comment by vitchyr** [comment]
Closed with d3ea8168be40635317cbb1dc4ec9f292dee414a1
