### ISSUE TITLE
SAC HER example results not matching

### ISSUE THREAD

**Issue by Shade5** [vitchyr/rlkit#49]
I cloned the repo, setup the environment and ran (made no changes)

`python her_sac_gym_fetch_reach.py`

The results don't seem to match with [this](https://github.com/vitchyr/rlkit/blob/master/docs/HER.md). Did something break in the latest commit? 

![image](https://user-images.githubusercontent.com/13672946/56505206-037a1200-64e9-11e9-8c72-c9d56ca88479.png)

However, when I try the td3, it works fine

`python her_td3_multiworld_sawyer_reach.py`

![image](https://user-images.githubusercontent.com/13672946/56505688-4ee0f000-64ea-11e9-9baf-e209b4847e1b.png)

**Comment by vitchyr** [comment]
Can you run multiple seeds? I included 5 separate runs since it does tend to fail sometimes.

**Comment by Shade5** [comment]
Sorry, but I can't seem to find the right place to set the seeds. Would you link me to a line number?

**Comment by vitchyr** [comment]
It should be set randomly so you can just run the script again.

**Comment by Shade5** [comment]
Yes, some of them work now, thanks.

![image](https://user-images.githubusercontent.com/13672946/56540956-3697c200-6538-11e9-9fec-11f996d41a97.png)

**Comment by Shade5** [comment]
On a side note, I was trying FetchPush-v1. The only changes I need to make is in gym.make(... ) right?

If so, I've tried multiple seeds with about 500 iterations, with no progress. Am I missing something? What's the expected time?

**Comment by vitchyr** [comment]
Based on [this paper](https://arxiv.org/abs/1802.09464), it seems like you need one millions steps, so probably (1000 iterations).

But they also use DDPG with an epsilon greedy exploration policy, so that might matter.

**Comment by Shade5** [comment]
For other users to confirm their results, here's FetchPush-v1 for 3 seeds.
![image](https://user-images.githubusercontent.com/13672946/56850717-33079080-68d4-11e9-8a1f-270e827dc21e.png)

Here's the results for 3 seeds on FetchPickAndPlace-v1
![image](https://user-images.githubusercontent.com/13672946/56850697-f2a81280-68d3-11e9-9654-03b7187e2673.png)
