### ISSUE TITLE
Multitask environment file does not exist

### ISSUE THREAD

**Issue by canercak** [vitchyr/rlkit#55]
Hi,
I am trying to implement TDM. The link for multitask env is broken. 
https://github.com/vitchyr/rlkit/blob/master/docs/envs/multitask_env.py

**Comment by vitchyr** [comment]
Did you checkout the v0.1.2 branch?

**Comment by canercak** [comment]
I only see the master branch but I just checked v0.1.2 and v.0.2.0 tags and I don't see it in "docs/envs" or  "rlkit/envs/"

**Comment by wudongming97** [comment]
Hi! Have you solved it?

**Comment by wudongming97** [comment]
> I only see the master branch but I just checked v0.1.2 and v.0.2.0 tags and I don't see it in "docs/envs" or "rlkit/envs/"

Hello! Have you solved it?

**Comment by canercak** [comment]
> > I only see the master branch but I just checked v0.1.2 and v.0.2.0 tags and I don't see it in "docs/envs" or "rlkit/envs/"
> 
> Hello! Have you solved it?

no I still don't see it

**Comment by vitchyr** [comment]
What script is calling this file? Or where is this link coming from? Perhaps the should be painting to the multiworld repository rather than rlkit.

**Comment by wudongming97** [comment]
> What script is calling this file? Or where is this link coming from? Perhaps the should be painting to the multiworld repository rather than rlkit.

Thanks for your replay! I solve the problem. This file is not in this repository. I pip mutiworld with other repository in github.

**Comment by vitchyr** [comment]
Closing since it seems the problem was that the file is found in another repo.
