### ISSUE TITLE
DDPG example - Missing TorchRLAlgorithm, how to use BatchRLDatasetAlgorithm

### ISSUE THREAD

**Issue by NarasimhaM3101** [vitchyr/rlkit#58]
DDPG class imports the following. But this class is missing. Typos?
from rlkit.torch.torch_rl_algorithm import TorchRLAlgorithm. And, the initialization function of DDPG /DDPG doesn't look complete.

Thanks,
Narasimha

**Comment by vitchyr** [comment]
Thanks for pointing this out. Fixed with 42a199e0eee66435a485a2226fec13bcd6578e18
