### ISSUE TITLE
Compatibility with pytorch 1.0

### ISSUE THREAD

**Issue by NarasimhaM3101** [vitchyr/rlkit#59]
Hi,

Any plan on updating the classes to be compatible with pytorch 1.0?

**Comment by vitchyr** [comment]
Is there any issue you have in mind? I have a slightly different version of the code that I've been using, and I was able to switch to PyTorch 1.0 without any changes.

**Comment by vitchyr** [comment]
Closing now since I think this is a non-issue. Feel free to open this again if you have issues with pytorch 1.0.
