### ISSUE TITLE
where is the skew-fit coresponding code

### ISSUE THREAD

**Issue by ZiwenZhuang** [vitchyr/rlkit#69]
I am trying to understand your code referring to paper [skew-fit: state-covering self-supervised reinforcement learning](https://arxiv.org/abs/1903.03698), but could not find out where it is implemented the repo?
Could you please give me more implementation details?
Thanks,

**Comment by vitchyr** [comment]
An [example script](https://github.com/vitchyr/rlkit/blob/master/examples/skewfit/sawyer_door.py) is listed in the [README.md](https://github.com/vitchyr/rlkit/blob/master/README.md).

**Comment by ZiwenZhuang** [comment]
Sorry that I didn't make myself clear. I mean the code that relates to the math computation in the paper.

**Comment by vitchyr** [comment]
Ah, I see.

See this part of the code: https://github.com/vitchyr/rlkit/blob/ae49265ef049c6b6d6be4fd3b2c76c5131c9b0ce/rlkit/torch/vae/vae_trainer.py#L80

**Comment by ZiwenZhuang** [comment]
Thank you very much. That helps a lot!
