### ISSUE TITLE
How do we set reward scale for SAC

### ISSUE THREAD

**Issue by qizhg** [vitchyr/rlkit#7]
For soft actor-critic, how do we specify the reward scale?
How do we specify it in `examples/sac.py`?

**Comment by vitchyr** [comment]
You can set `reward_scale` in [`algo_params`](https://github.com/vitchyr/rlkit/blob/master/examples/sac.py#L57), i.e.

```
algo_params = dict(
  reward_scale=123,
  ...
)
```

For more detail: it's passed in as a [`kwarg`](https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/sac/sac.py#L33) to [`RLAlgorithm`](https://github.com/vitchyr/rlkit/blob/master/rlkit/core/rl_algorithm.py#L29).
