### ISSUE TITLE
No data file is being created and filed with new SAC trainings

### ISSUE THREAD

**Issue by nanbaima** [vitchyr/rlkit#77]
I was using the previous version of SAC, it was working fine regarding creating the `/data` file and filling it with the training episodes.
However the new version is not creating neither felling this file.
At the `sac.py` at `setup_logger('name-of-experiment', variant=variant, log_dir='./data/name')` I added the `log_dir='./data'` in order to create the `./data` file and fill it with the current SAC being trained.
I have no clue what so ever might had happened. Did anybody see anything alike? Any suggestions?

**Comment by vitchyr** [comment]
I haven't seen this. Maybe try using an absolute path first to see if that's an issue? The other thing I would suggest is putting an `ipdb.set_trace()` [(see this example for how to use `ipdb`)](https://gist.github.com/mono0926/6326015) in the logger file where it creates the log directory.

**Comment by nanbaima** [comment]
Hey Vitchyr,
To be fair, I don´t know what solved the problem, but those new versions implementations are now working just fine.
