### ISSUE TITLE
Getting a gtimer error while installing requirements

### ISSUE THREAD

**Issue by sir-avinash** [vitchyr/rlkit#8]
Hi Vitchyr,
I'm following your rlkit-gpu install instructions (i.e., conda env create -f docker/rlkit_gpu/rlkit-env.yml), and I get the following error:

Could not find a version that satisfies the requirement gtimer==1.0.1b5 (from -r /data/repos/rlkit/docker/rlkit_gpu/condaenv.27ccrza6.requirements.txt (line 4)) (from versions: 1.0.0b0, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0b5)
No matching distribution found for gtimer==1.0.1b5 (from -r /data/repos/rlkit/docker/rlkit_gpu/condaenv.27ccrza6.requirements.txt (line 4))

Please help :-/

**Comment by vitchyr** [comment]
I updated the `.yml` file to use 1.0.0b5, which should work. If not, please re-open this issue.

**Comment by sir-avinash** [comment]
Thanks, that worked. Found another related issue going forward. Pytorch 0.4.0 throws the following error - "RecursionError: maximum recursion depth exceeded". Online jedi suggest using 0.3.1 as a fix [https://github.com/allenai/allennlp/issues/1161](url). Might want to update .yml file accordingly :-)

**Comment by sir-avinash** [comment]
[](url)
