### ISSUE TITLE
self.custom_goal_sample is None

### ISSUE THREAD

**Issue by Jingjinganhao** [vitchyr/rlkit#84]
I set power = 0 and run sawyer_pickup.py.
When I run 
python scripts/run_goal_conditioned_policy.py  <myfoldername>/params.pkl
,it shows 
return self.custom_goal_sample(batch_size)
TypeError:'NoneType' object is not callable
How can I fix it?
Thanks!

**Comment by vitchyr** [comment]
Hmmm, can you see what happens if you don't use the custom goal sampler? Also, it'd be helpful if posted the more complete stack-trace.

**Comment by Jingjinganhao** [comment]
Thank you for your reply!
What can I do to not use the custom goal sampler?
Should I change exploration_goal_sampling_mode='custom_goal_sampler' in sawyer_pickup.py ?
How can I change it?
Can you say more details
Thanks!

**Comment by vitchyr** [comment]
Not sure if this is still relevant, but yes, you can set the goal sampling mode to something like, such as:
```
env.goal_sampling_mode = 'env'
```
