### ISSUE TITLE
question about the seed args

### ISSUE THREAD

**Issue by wayunderfoot** [vitchyr/rlkit#85]
I have lots of interests in deepRL,in particular the SAC algorithm.But i can not find the seed args explicitly,could anyone help me figure out what is the function of seed,thanks!

**Comment by vitchyr** [comment]
It's generated in launcher utils

**Comment by wayunderfoot** [comment]
Firstly thanks for your quickly reply and contribution to open source.  I am feeling very sorry for not seeing your reply immediately.But i can't find the call to run_experiment and run_experient_here in SAC impletition from example/sac.py.could you clarify it to me?I am a beginner for pytorch and DRL feeling appreciated getting your reply,thanks!

**Comment by vitchyr** [comment]
Ah, good point! The example doesn't called `run_experiment`. Yes, so it looks like I don't explicitly set the seed in those example scripts. Frankly, I tend not to worry about the different seeds (I think by default they're randomly initialized).

If you do want to set the seed yourself, I recommend looking at:  https://pytorch.org/docs/stable/notes/randomness.html

**Comment by wayunderfoot** [comment]
Very grateful for such a quick reply.
