### ISSUE TITLE
Difference bewteen creating environments by different methods

### ISSUE THREAD

**Issue by wayunderfoot** [vitchyr/rlkit#88]
First thanks for your well understanding code.
for example:
https://github.com/vitchyr/rlkit/blob/1d469a509b797ca04a39b8734c1816ca7d108fc8/examples/ddpg.py#L25
is this imposing a big difference to algorithm performence?

**Comment by vitchyr** [comment]
Not in my experience. Have you found it to matter?

**Comment by wayunderfoot** [comment]
Having not done enough experiment,it's hard to see.I am just curious about it.
