### ISSUE TITLE
key error when run_policy

### ISSUE THREAD

**Issue by ChenyangRan** [vitchyr/rlkit#99]
Hi, I'm a beginner, and meet an error when testing the result.
I have trained the _**example/her/her__sac_gym_fetch_reacher.py.**_
I want to see the winow which showing the model, so I run the **_run_policy.py_**.
However, the error is _**'key error'**_, and I haven't changed the code.
Is there anyone help me?
I have set the ptu.set_gpu_mode(True) to use GPU.
![1584785675(1)](https://user-images.githubusercontent.com/29306735/77224379-0de0d800-6ba0-11ea-9fd4-c50b87b6fa3d.jpg)

**Comment by vitchyr** [comment]
You should use the `run_goal_conditioned_policy.py` script instead of the `run_policy.py` script. Thanks for pointing that out. I've updated the README.

**Comment by ChenyangRan** [comment]
> You should use the `run_goal_conditioned_policy.py` script instead of the `run_policy.py` script. Thanks for pointing that out. I've updated the README.

Thanks for your replay, but still errors when **### run_goal_conditioned_policy.py.**
I print the **data['evaluation/env']**, it's the num.
Could you please help me again?
I just use the cmd when training and the paras are default.
``` shell
python example/her/her__sac_gym_fetch_reacher.py
```
Should I change something else?

![image](https://user-images.githubusercontent.com/29306735/77240180-ef212680-6c1d-11ea-8400-fc1dbe56084c.png)

**Comment by vitchyr** [comment]
Thanks. I fixed the script to use `torch.load` rather than `pickle.load`.

**Comment by ChenyangRan** [comment]
> Thanks. I fixed the script to use `torch.load` rather than `pickle.load`.

It works well.
Thanks very much.
